Changes made to sql Fact files
palladiumkenya/dwh-etl-edw-spark-jobs pull request #14
Opened 2024-05-01 12:28 UTC by NewtonMutugi

2024-05-09 12:06 UTC, cbrianbet requested changes

2024-05-09 12:08 UTC, NewtonMutugi commented on Load Fact TxCurr Concordance/src/main/resources/LoadFactTxCurrConcordance.sql
> +    left join NDWH.dbo.DimFacility as facility on facility.MFLCode = Summary.MFLCode
Okay hadn't seen it. Let me make the change

2024-05-13 07:55 UTC, nthusi-codes approved these changes
LGTM!
Try and have smaller PRs with key update/feature. eg a small PR  focused on just PBFW updates etc. This is for next time.

2024-05-13 07:56 UTC, NewtonMutugi commented
This is noted. Thanks

2024-05-13 14:02 UTC, merged