Updated EDW Scripts
palladiumkenya/dwh-etl-edw-spark-jobs pull request #9
Opened 2024-02-12 07:18 UTC by cbrianbet

2024-02-17 11:40 UTC, cbrianbet commented on Load Fact ART History/src/main/java/org/kenyahmis/loadarthistoryfact/LoadARTHistoryFact.java
>                  .option("dbtable", "dbo.HistoricalARTOutcomesBaseTable")
@nthusi-codes 
We might have to create a config for this

2024-02-21 17:26 UTC, nthusi-codes approved these changes
LGTM. Note the airflow dag comment

2024-02-21 17:26 UTC, nthusi-codes commented on Load Fact Ushauri Appointments/src/main/java/org/kenyahmis/loadfactushauriappointments/LoadFactUshauriAppointments.java
> +                .load();
This might fail as there are no ushauri scripts in the spark etl. You may have to skip this task in the edw dag

2024-02-21 17:50 UTC, nthusi-codes requested changes
The POM files don't seem to have the build stage. How are the runnable jars generated?

2024-02-21 17:50 UTC, nthusi-codes commented on Load Fact ART History/src/main/java/org/kenyahmis/loadarthistoryfact/LoadARTHistoryFact.java
>                  .option("dbtable", "dbo.HistoricalARTOutcomesBaseTable")
noted

2024-02-27 07:46 UTC, nthusi-codes approved these changes

2024-02-28 11:33 UTC, merged